### ISSUE TITLE
Probe result numbers should probably be rounded at some point

### ISSUE THREAD

**Issue by mnalis** [nukebloodaxe/Ironseed-py#4] opened 2020-10-09 19:16 UTC
**Describe the bug**
Please provide a clear and concise description of what the bug is.  The more information you provide, the easier it is for me to find where the problem is being created in the code.

**To Reproduce**
Please describe the steps to reproduce the behaviour:
1. Start new game
2. Click on "land", "sea", "air", "life", "anom" and wait for probes to return after each one
3. Observe results like "Atmosferic pressure: 4.1999999999999999999 Atm"

**Expected behaviour**
It should probable be more like "Atmosferic pressure: 4.19 Atm" or "4.2 Atm" or whatever precision is reasonable

**Screenshots**
![probe-numbers](https://user-images.githubusercontent.com/156656/95622842-92c80c00-0a74-11eb-9af8-bb3fcf362f01.png)

**Comment by nukebloodaxe** [comment] 2020-10-10 09:54
Duplicate of #5

**Closed by nukebloodaxe** 2020-10-10 09:54 UTC
Labels: bug, duplicate
